[package]
name = "coffeekernel"
version = "0.1.0"
edition = "2024"

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[unstable]
build-std-features = ["compiler_builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86-64.json"